bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import (index,
                    BbIndexView, BbMonthView, BbByRubricView,
                    BbCreateView, BbDetailView, BbEditView, BbDeleteView,
                    BbRedirectView, edit, add_save, rubrics, bbs, search, api_rubrics, api_rubrics_detail, api_bbs,
    # APIRubrics, APIRubricsDetail
                    APIRubricViewSet, api_bbs_detail, )


app_name = 'bboard'

router = DefaultRouter()
router.register('rubrics', APIRubricViewSet)

urlpatterns = [
    # path('api/v1/rubrics/<int:pk>/', api_rubrics_detail),
    # path('api/v1/rubrics/<int:pk>/', APIRubricsDetail.as_view()),

    path('api/v1/rubrics/', api_rubrics),
    # path('api/v1/rubrics/', APIRubrics.as_view()),

    # api/v1/rubrics/ - GET, POST
    # api/v1/rubrics/pk/ - GET, PUT, PATCH, DELETE
    path('api/', include(router.urls)),

    path('api/bbs/', api_bbs),
    path('api/bbs/<int:pk>/', api_bbs_detail),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('add/save/', add_save, name='add_save'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('update/<int:pk>/', BbEditView.as_view(), name='update'),
    # path('update/<int:pk>/', edit, name='update'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    # path('<int:rubric_id>/', cache_page(10)(BbByRubricView.as_view()), name='by_rubric'),

    path('', index, name='index'),
    # path('', BbIndexView.as_view(), name='index'),
    path('year/<int:year>/', BbRedirectView.as_view(), name='redirect'),
    path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('search/', search, name='search'),
]

samplesite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/v1/drf-auth/', include('rest_framework.urls')),

    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),

    path('test/', include('testapp.urls', namespace='test')),
    path('', include('bboard.urls', namespace='bboard')),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bboard/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

from .models import Bb as BbModel, Rubric, IceCream


class BbForm(forms.ModelForm):
    title = forms.CharField(label='Название товара',
                            validators=[validators.RegexValidator(regex='^.{4,}$')],
                            error_messages={'invalid': 'Короткое название товара!'})
    content = forms.CharField(label='Описание', widget=forms.widgets.Textarea())
    price = forms.DecimalField(label='Цена', decimal_places=2)
    rubric = forms.ModelChoiceField(
        queryset=Rubric.objects.all(),
        label='Рубрика',
        help_text='Выберите рубрику!',
        widget=forms.widgets.Select(attrs={'size': 8})
    )

    def clean_title(self):
        val = self.cleaned_data.get('title')
        if val == 'Прошлогодний снег':
            raise ValidationError('К продаже не допускается!')
        return val

    def clean(self):
        super().clean()
        errors = {}
        if not self.cleaned_data.get('content'):
            errors['content'] = ValidationError('Укажите описание продоваемого товара')

        if self.cleaned_data.get('price') < 0:
            errors['price'] = ValidationError('Укажите корректное значение продоваемого товара')

        if errors:
            raise ValidationError(errors)

    class Meta:
        model = BbModel
        fields = ('title', 'content', 'price', 'picture')


class RegisterUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль')
    password2 = forms.CharField(label='Пароль (повторно)')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class IceCreamForm(forms.ModelForm):
    class Meta:
        model = IceCream
        fields = ('flavor', 'description', 'price', 'available')



class SearchForm(forms.Form):
    keyword = forms.CharField(max_length=20, label="Искомое слово")
    rubric = forms.ModelChoiceField(queryset=Rubric.objects.all(), label="Рубрика")
    captcha = CaptchaField(label='Введите текст с картинки', # error_mesages={'invalid': 'Неправильный текст'},
                           generator='captcha.helpers.word_challenge')

    error_css_class = 'error'
    required_css_class = 'required'

bboard/views.py
import logging

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import redirect_to_login
from django.core.cache import caches, cache
from django.core.exceptions import NON_FIELD_ERRORS
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Count
from django.forms import modelformset_factory, inlineformset_factory
from django.forms.formsets import ORDERING_FIELD_NAME
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView, TemplateView
from django.views.generic.dates import ArchiveIndexView, MonthArchiveView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from precise_bbcode.bbcode import get_parser
from rest_framework import status, generics
from rest_framework.authentication import TokenAuthentication
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from django.core.signing import Signer

from bboard.serializers import RubricSerializer
from .forms import BbForm, RubricBaseFormSet, SearchForm
from .models import Bb, Rubric


logger = logging.getLogger(__name__)


# @cache_page(60 * 5)
def index(request):

    logger.warning('Хаюшки!')

    bbs = Bb.objects.all()

    # bbs = cache.get('bbs_cache_key') # --REDIS

    # if bbs is None:
    #     bbs = list(Bb.objects.all())
    #     cache.set('bbs_cache_key', bbs, timeout=300)  # Кеширование данных на 5 минут --REDIS

    paginator = Paginator(bbs, 2, orphans=2)
    # paginator = Paginator(bbs, 1, orphans=0)

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1

    # if 'counter' in request.COOKIES:
    #     cnt = int(request.COOKIES['counter']) + 1
    # else:
    #     cnt = 1

    if 'counter' in request.session:
        cnt = int(request.session['counter']) + 1
    else:
        cnt = 1

    request.session['counter'] = cnt

    print('cnt =', cnt)

    page = paginator.get_page(page_num)

    context = {'page_obj': page, 'bbs': page.object_list}

    response = render(request, 'index.html', context)
    response.set_cookie('counter', cnt)
    # response.set_signed_cookie('counter', cnt, salt=settings.SECRET_KEY)
    # response.get_signed_cookie('counter', salt=settings.SECRET_KEY)

    return response


class BbIndexView(ListView):
# class BbIndexView(LoginRequiredMixin, ListView):
    model = Bb
    template_name = 'index.html'
    context_object_name = 'bbs'
    paginate_by = 1
    paginate_orphans = 2

    def get_queryset(self):
        return Bb.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'counter' in self.request.COOKIES:
            cnt = int(self.request.COOKIES['counter']) + 1
        else:
            cnt = 1
        return context


# class BbIndexView(ArchiveIndexView):
#     model = Bb
#     template_name = 'index.html'
#     date_field = 'published'
#     date_list_period = 'month'
#     context_object_name = 'bbs'
#     allow_empty = True
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
#         return context


class BbMonthView(MonthArchiveView):
    model = Bb
    template_name = 'index.html'
    date_field = 'published'
    date_list_period = 'month'
    month_format = '%m'
    context_object_name = 'bbs'
    allow_empty = True

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['rubrics'] = Rubric.objects.all()
    #     return context


class BbRedirectView(RedirectView):
    url = '/'


class BbByRubricView(ListView):
    template_name = 'by_rubric.html'
    context_object_name = 'bbs'

    def get_queryset(self):
        return Bb.objects.filter(rubric=self.kwargs['rubric_id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['rubrics'] = Rubric.objects.all()

        # cache.set('current_rubric', Rubric.objects.get(
        #     pk=self.kwargs['rubric_id']))
        # print(cache.get('current_rubric'))
        # cache.delete('current_rubric')
        # print(cache.get('current_rubric'))
        #
        # cache.clear()

        context['current_rubric'] = Rubric.objects.get(
            pk=self.kwargs['rubric_id'])
        return context


class BbDetailView(DetailView):
    model = Bb

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['rubrics'] = Rubric.objects.all()
    #     return context


def detail(request, pk):
    parser = get_parser()
    bb = Bb.objects.get(pk=pk)
    parsed_content = parser.render(bb.content)
    pass


class BbCreateView(CreateView):
    template_name = 'create.html'
    form_class = BbForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['rubrics'] = Rubric.objects.all()
        context['messages'] = ['Ага, ты молодес!']

        return context


class BbEditView(UpdateView):
    model = Bb
    form_class = BbForm
    # success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        CRITICAL = 50

        messages.add_message(self.request, messages.SUCCESS,
                             'Объявление исправлено!', extra_tags='first second')
        messages.add_message(self.request, CRITICAL, 'Случилось непоправимое!')
        # messages.success(self.request, 'Объявление исправлено!') # Всплывающие уведомления
        return context

    def get_success_url(self):
        return reverse_lazy('bboard:update', kwargs={'pk': self.kwargs['pk']})


class BbDeleteView(DeleteView):
    model = Bb
    success_url = '/'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['rubric'] = Rubric.objects.all()
    #     return context

# Подпись данных
# def edit(request, pk):
#     bb = Bb.objects.get(pk=pk)
#
#     if request.method == 'POST':
#         bbf = BbForm(request.POST, instance=bb)
#         if bbf.is_valid():
#             if bbf.has_changed():
#                 signer = Signer()
#                 signed_data = signer.sign(str(bbf.cleaned_data))  # Подпись данных
#                 bbf.save()
#                 return HttpResponseRedirect(
#                     reverse('bboard:detail', kwargs={'pk': pk})
#                 )
#             else:
#                 bbf.save()
#                 return HttpResponseRedirect(
#                     reverse('bboard:detail', kwargs={'pk': pk})
#                 )
#         else:
#             context = {'form': bbf}
#             return render(request, 'bboard/bb_form.html', context)
#     else:
#         bbf = BbForm(instance=bb)
#         context = {'form': bbf}
#         return render(request, 'bboard/bb_form.html', context)

def edit(request, pk):
    bb = Bb.objects.get(pk=pk)

    if request.method == 'POST':
        bbf = BbForm(request.POST, instance=bb)
        if bbf.is_valid():
            if bbf.has_changed():
                bbf.save()
            return HttpResponseRedirect(
                # reverse('bboard:by_rubric',
                #         kwargs={'rubric_id': bbf.cleaned_data['rubric'].pk})
                reverse('bboard:detail',
                        kwargs={'pk': pk})
            )
        else:
            context = {'form': bbf}
            return render(request, 'bboard/bb_form.html', context)
    else:
        bbf = BbForm(instance=bb)
        context = {'form': bbf}
        return render(request, 'bboard/bb_form.html', context)


def add_save(request):
    bbf = BbForm(request.POST)

    if bbf.is_valid():
        bbf.save()
        return HttpResponseRedirect(
            reverse('bboard:by_rubric',
                    kwargs={'rubric_id': bbf.cleaned_data['rubric'].pk})
        )
    else:
        context = {'form': bbf}
        return render(request, 'bboard/bb_form.html', context)


# def commit_handler():
#     print("C O M M I T E D")


def rubrics(request):
    RubricFormSet = modelformset_factory(Rubric, fields=('name',), can_order=True,
                                         can_delete=True, extra=3, formset=RubricBaseFormSet)

    if request.method == 'POST':
        formset = RubricFormSet(request.POST)

        if formset.is_valid():
            instances = formset.save(commit=False)
            for obj in formset:
                if obj.cleaned_data:
                    # sp = transaction.savepoint()

                    try:
                        rubric = obj.save(commit=False)
                        rubric.order = obj.cleaned_data[ORDERING_FIELD_NAME]
                        rubric.save()
                        # transaction.savepoint_commit(sp)
                        print("C O M M I T E D", rubric, type(rubric))
                    except:
                        # transaction.savepoint_rollback(sp)

templates/bboard/bb_confirm_delete.html
{% extends "layout/basic.html" %}

{% block title %}Удаление объявления{% endblock %}

{% block content %}
    <h2>Удаления объявления</h2>
    
    <p>Рубрика: {{ bb.rubric.name }}</p>
    <p>Товар: {{ bb.title }}</p>
    <p>{{ bb.content }}</p>
    <p>Цена: {{ bb.price }}</p>
    

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
{% endblock %}

templates/bboard/bb_detail.html
{% extends 'layout/basic.html' %}
{% load bbcode_tags %}
{% load thumbnail %}

{% block title %}{{ bb.title }}{% endblock %}

{% block content %}
    <p>Рубрика: {{ bb.rubric.name|title }}</p>
    <h2>{{ bb.title }}</h2>

    <img src="{% thumbnail bb.picture 'default' %}" alt="">
    
{#    {% bbcode bb.content %}#}
    
    {{ bb.content|bbcode|safe }}
    
    <p>{{ bb.content }} ({{ bb.content|wordcount }} слов) ({{ bb.content|length }} символов)</p>
    <p>Цена: {{ bb.price|floatformat:2|default:'У товара нет цены' }}</p>
    
    <p>
        <a href="{% url 'bboard:update' bb.pk %}">Изменить</a>
        <a href="{% url 'bboard:delete' bb.pk %}">Удалить</a>
    </p>
{% endblock %}

templates/bboard/bb_form.html
{% extends "layout/basic.html" %}

{% block title %}Изменение объявления{% endblock %}

{% block content %}
    <h2>Изменение объявления</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
    
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
    
        {% if form.non_field_errors %}
            <ul>
                {% for error in form.non_field_errors %}
                    <li><em>{{ error|escape }}</em></li>
                {% endfor %}
            </ul>
        {% endif %}
    
    {% for field in form.visible_fields %}
        {% if field.errors %}
        	<ul>
                {% for error in field.errors %}
                    <li><em>{{ error|escape }}</em></li>
                {% endfor %}
            </ul>
        {% endif %} 
        <p>{{ field.label_tag }}<br>{{ field }}<br>{{ field.help_text }}</p>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Изменить</button></p>
    </form>
{% endblock %}  

templates/bboard/bbs.html
{% extends "layout/basic.html" %}

{% block title %}Изменение объявлений рубрики {{ current_rubric }}{% endblock %}

{% block content %}
    <h2>Изменение объявлений рубрики {{ current_rubric }}</h2>

    <form method="post">
        {% csrf_token %}
        {{ formset.as_p }}
    <p><button type="submit" class="btn btn-primary">Сохранить</button></p>
    </form>
{% endblock %}  

templates/bboard/ice_cream.html
{% extends "layout/basic.html" %}

{% block title %}Добавления мороженого{% endblock %}

{% block content %}
    <h2>Добавление мороженого</h2>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><button type="submit" class="btn btn-primary">Добавить</button></p>
    </form>
{% endblock %}  

templates/bboard/rubrics.html
{% extends "layout/basic.html" %}

{% block title %}Изменение рубрик{% endblock %}

{% block content %}
    <h2>Изменение рубрики</h2>

    <form method="post">
        {% csrf_token %}

        {{{ formset.management_form }}

        {% if formset.non_form_errors %}
            <ul>
                {% for error in formset.non_form_errors %}

                {% endfor %}
            </ul>
        {% endif %}

        <p>
            <button type="submit" class="btn btn-primary">Изменить</button>
        </p>
    </form>}
{% endblock %}  

templates/bboard/search.html
{% extends "layout/basic.html" %}

{% block title %}Поиск объявлений{% endblock %}

{% block content %}
    <h2>Поиск объявлений</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <button type="submit" class="btn btn-primary">Найти</button>
        </p>
    </form>
{% endblock %}

templates/bboard/search_result.html
{% extends "layout/basic.html" %}

{% block content %}
    <h2>Рубрика: {{ current_rubric.name }}</h2>
    <h2>Результаты поиска по слову: &laquo {{ keyword }} &raquo</h2>

    {% for bb in bbs %}
    <div>
        <h2><a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}