bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import (index,
                    BbIndexView, BbMonthView, BbByRubricView,
                    BbCreateView, BbDetailView, BbEditView, BbDeleteView,
                    BbRedirectView, edit, add_save, rubrics, bbs, search, api_rubrics, api_rubrics_detail, api_bbs,
    # APIRubrics, APIRubricsDetail
                    APIRubricViewSet, api_bbs_detail, )


app_name = 'bboard'

router = DefaultRouter()
router.register('rubrics', APIRubricViewSet)

urlpatterns = [
    # path('api/v1/rubrics/<int:pk>/', api_rubrics_detail),
    # path('api/v1/rubrics/<int:pk>/', APIRubricsDetail.as_view()),

    path('api/v1/rubrics/', api_rubrics),
    # path('api/v1/rubrics/', APIRubrics.as_view()),

    # api/v1/rubrics/ - GET, POST
    # api/v1/rubrics/pk/ - GET, PUT, PATCH, DELETE
    path('api/', include(router.urls)),

    path('api/bbs/', api_bbs),
    path('api/bbs/<int:pk>/', api_bbs_detail),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('add/save/', add_save, name='add_save'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('update/<int:pk>/', BbEditView.as_view(), name='update'),
    # path('update/<int:pk>/', edit, name='update'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    # path('<int:rubric_id>/', cache_page(10)(BbByRubricView.as_view()), name='by_rubric'),

    path('', index, name='index'),
    # path('', BbIndexView.as_view(), name='index'),
    path('year/<int:year>/', BbRedirectView.as_view(), name='redirect'),
    path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('search/', search, name='search'),
]

samplesite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/v1/drf-auth/', include('rest_framework.urls')),

    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),

    path('test/', include('testapp.urls', namespace='test')),
    path('', include('bboard.urls', namespace='bboard')),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/_inc_paginator.html
{#<div>#}
{#    {% if page.has_previous %}#}
{#        <a href="?page={{ page.previous_page_number }}">&lt;</a>#}
{#        &nbsp; &nbsp; | &nbsp; &nbsp;#}
{#    {% endif %}#}
{##}
{#    Страница №{{ page.number }} из {{ page.paginator.num_pages }}#}
{##}
{#    {% if page.has_next %}#}
{#        &nbsp; &nbsp; | &nbsp; &nbsp;#}
{#        <a href="?page={{ page.next_page_number }}">&gt;</a>#}
{#    {% endif %}#}
{#</div>#}

{% if page.has_other_pages %}
    <nav aria-label="pagination">
        <ul class="pagination">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}">Назад</a>
                </li>
            {% endif %}

            {% for p in page.paginator.page_range %}
                {% if not p == page.number %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link disabled bg-primary text-light" href="?page={{ p }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}">Вперед</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/includes/inc_footer.html
<footer>&copy;1982 &ndash; {% now 'Y' %}</footer>

templates/includes/inc_header.html
{% load static %}
{% load bootstrap4 %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %} :: Доска объявлений</title>
{#    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">#}
    {% bootstrap_css %}

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

templates/includes/inc_main_menu.html
<nav>
    <a href="{% url 'bboard:index' %}">Главная</a>
    <a href="{% url 'bboard:add' %}">Добавить</a>
    <a href="{% url 'bboard:login' %}">Войти</a>
    <a href="{% url 'bboard:all_users' %}">All Users</a>
    <a href="{% url 'bboard:select_columns' %}">Select Columns</a>
    <a href="{% url 'bboard:exclude_values' %}">Exclude Values</a>
    <a href="{% url 'bboard:ice_cream' %}">Add Ice Cream</a>
    <a href=""></a>
    {% for rubric in rubrics %}
        {% with bb_count=rubric.count %}
            <a href="{{ rubric.get_absolute_url }}">
                {#                {{ rubric.name }} ({{ rubric.count }})</a>#}
                {% filter force_escape|upper %}
                    {{ rubric.name }}
                {% endfilter %}
                ({{ bb_count }})</a>
        {% endwith %}
    {% endfor %}
</nav>

templates/includes/inc_paginator.html
{% load bootstrap4 %}

{% bootstrap_pagination page_obj pages_to_show=3 %}

{% if page_obj.has_other_pages %}
    <nav aria-label="pagination">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Назад</a>
                </li>
            {% endif %}

            {% for p in page_obj.paginator.page_range %}
                {% if not p == page_obj.number %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link disabled bg-primary text-light" href="?page={{ p }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперед</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}