bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import (index,
                    BbIndexView, BbMonthView, BbByRubricView,
                    BbCreateView, BbDetailView, BbEditView, BbDeleteView,
                    BbRedirectView, edit, add_save, rubrics, bbs, search, api_rubrics, api_rubrics_detail, api_bbs,
    # APIRubrics, APIRubricsDetail
                    APIRubricViewSet, api_bbs_detail, )


app_name = 'bboard'

router = DefaultRouter()
router.register('rubrics', APIRubricViewSet)

urlpatterns = [
    # path('api/v1/rubrics/<int:pk>/', api_rubrics_detail),
    # path('api/v1/rubrics/<int:pk>/', APIRubricsDetail.as_view()),

    path('api/v1/rubrics/', api_rubrics),
    # path('api/v1/rubrics/', APIRubrics.as_view()),

    # api/v1/rubrics/ - GET, POST
    # api/v1/rubrics/pk/ - GET, PUT, PATCH, DELETE
    path('api/', include(router.urls)),

    path('api/bbs/', api_bbs),
    path('api/bbs/<int:pk>/', api_bbs_detail),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('add/save/', add_save, name='add_save'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('update/<int:pk>/', BbEditView.as_view(), name='update'),
    # path('update/<int:pk>/', edit, name='update'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    # path('<int:rubric_id>/', cache_page(10)(BbByRubricView.as_view()), name='by_rubric'),

    path('', index, name='index'),
    # path('', BbIndexView.as_view(), name='index'),
    path('year/<int:year>/', BbRedirectView.as_view(), name='redirect'),
    path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('search/', search, name='search'),
]

samplesite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/v1/drf-auth/', include('rest_framework.urls')),

    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),

    path('test/', include('testapp.urls', namespace='test')),
    path('', include('bboard.urls', namespace='bboard')),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/all_users.html
<!DOCTYPE html>
<html>
<head>
    <title>All Users</title>
</head>
<body>
    <h1>All Users</h1>
    <ul>
        {% for user in users %}
            <li><a href="{% url 'bboard:user_profile' pk=user.id %}">{{ user.username }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

templates/by_rubric.html
{% extends "layout/basic.html" %}

{% block content %}
    <h2>Рубрика: {{ current_rubric.name }}</h2>

    {% for bb in bbs %}
    <div>
        <h2><a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

templates/create.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}

    {% bootstrap_alert content='!' alert_type='danger' %}
    <h2>Добавления объявление</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
{#        {% bootstrap_form form %}#}
{#        {% bootstrap_form form layout='inline' field_class='col-md-6' size='small'%}#}
{#        {% bootstrap_field form.title placeholder='Placeholder' addon_before='@' addon_after='.'%}#}
            {% bootstrap_form form %}
{#        {% buttons submit='Добавить' %}{% endbuttons %}#}
        {% bootstrap_button content='Добавить' button_type='submit' button_class='btn-primary'%}
    </form>

{% endblock %}

templates/exclude_values.html
{% extends "layout/basic.html" %}
{% block title %}Объявления с ценой меньше или равно 100500{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Title</th>
            <th>Rubric</th>
            <th>Price</th>
            <th>Published</th>
        </tr>
        {% for bb in bbs %}
            {{ bb }}
            <tr>
                <td>{{ bb.title }}</td>
                <td>{{ bb.rubric }}</td>
                <td>{{ bb.price }}</td>
                <td>{{ bb.published }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/index.html
{% extends "layout/basic.html" %}
{% load filtertags %}
{% load bbcode_tags %}
{% load thumbnail %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}
{#    {% now "Y-m-d H:i:s" as current_datetime %}#}
{#    <h3>Entry Date and Time: {{ current_datetime }}</h3>#}
    <p>{% current_datetime "%Y-%m-%d %H:%M:%S" %}</p>
    
{#    {% lst ', ' '1' '2' '3' '4' '5' %}#}
    {% string_to_list ', ' '12345' %}
    {% ulist '1' '2' '3' '4' '5' %}
    
    {% for user_info in users_with_groups %}
        <li>{{ user_info.user.username }} - {% for group in user_info.groups %}{{ group.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    {% endfor %}
    
    <p>
        {% for d in date_list %}
            {{ d.year }} / <a href="{% url 'bboard:month' year=d.year month=d.month %}">{{ d.month }}</a>
        {% endfor %}
    </p>
    <p>{{ bb.content|bbcode|safe }}</p>
    {% for bb in bbs %}
        {% with index=forloop.counter0|add:page_obj.start_index %}
            <div class="{% cycle 'b1' 'b2' %}">
                <h2>{% url 'bboard:detail' bb.pk as detail_url %}
                    <a href="{{ detail_url }}">
                        {{ index }} - {{ bb.title_and_price|to_upper }}
                        {% if forloop.first %}
                            (Первое объявление)
                        {% elif forloop.last %}
                            (Последнее объявление)
                        {% endif %}
                    </a>
                </h2>

                <img src="{{ bb.picture|thumbnail_url:'default' }}" alt="">

                <p>{{ bb.content|truncatewords_html:5|wordwrap:1 }}</p>
                <p>{{ bb.content|truncate_half }}</p>
                {% autoescape on %}
                    <p>Цена: {{ bb.price|currency }}</p>
                    <p>Цена: {{ bb.price|currency:'руб.' }}</p>
                    <p>Состояние товара: {{ bb.item_status }}</p>
                {% endautoescape %}
                
                {% ifchanged bb.rubric.name %}
                    <p>
                       <a href="{#% url 'bboard:by_rubric' bb.rubric.pk %#}">
                            {{ bb.rubric.name }}</a>
                    </p>
                {% endifchanged %}

                <p>{{ bb.id_and_date }}</p>
            
                {% comment %}
                    This is a comment that will not be displayed in the final HTML.
                {% endcomment %}
            </div>
        {% endwith %}
    {% endfor %}
    {% include 'includes/inc_paginator.html' %}
{% endblock %}

templates/select_columns.html
{% extends "layout/basic.html" %}
{% block title %}Определенные поля{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Title</th>
            <th>Price</th>
        </tr>
        {% for bb in bbs %}
            <tr>
                <td>{{ bb.title }}</td>
                <td>{{ bb.price }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for bb in bbs %}
        <p>{{ bb }}</p>
    {% endfor %}
</body>
</html>

templates/user_profile.html
<!DOCTYPE html>
<html>
<head>
    <title>User Profile</title>
</head>
<body>
    <h1>User Profile</h1>
    <p>Username: {{ user.username }}</p>
</body>
</html>